Fix: `compatibility.preLoad`, `edition.preLoad`-"TypeError: name.matchAll is not a function. (In 'name.matchAll(this.reVars)', 'name.matchAll' is undefined)" in Safari (thrown in `klass.vars`). Cause: Safari doesn't support `String.matchAll` until v13. Soln: fill it in.