Fix: `compatibility.stream`-"TypeError: "','".join is not a function". Cause: wrong object & arguments. Soln: swap. Also broke up condition to avoid incorrect/inapplicable error message.