Fix: `compatibility.aliases=`-"TypeError: exporters[base] is not a function". Cause: some exporters in `aliases.jp12x_splat.export` are (string) references to other exporters. Soln: dereference properties of each DST exporter (and importer) bundle.