Fix: `aliases.cWoD_Revised.export._start`-"TypeError: compatibility.export.exportField is not a function". Cause: wrong path to function; shoud be `compatibility.exportField`. Soln: corrected path.