Fix: `pips.demi.countPips`-"TypeError: _pips.findLastIndex is not a function" in FireFox and pips can't be set by clicking. Cause: FF doesn't currently support `Array.findLastIndex` (though it's in-development). Soln: fill it in.